In [1]:
import pandas as pd

df_account = pd.read_csv(r"C:\Users\sudhanshu\Downloads\AML DATAset\HI-Medium_accounts.csv")

df_account.shape

(2087786, 5)

In [2]:
df_account.duplicated().sum()

np.int64(0)

In [3]:
df_account.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,China Bank #561,53267,817D00980,2AA1F24F180,Corporation #183669
1,Spain Bank #18657,316997,808BB2280,2AA1EEB8540,Partnership #193780
2,First Bank of Helena,339367,8505ED380,2AA206D7790,Sole Proprietorship #4078
3,Mexico Bank #3367,3148419,8363D4180,2AA2001B1A0,Partnership #133577
4,Switzerland Bank #2372,3174937,842090C80,2AA20224CB0,Sole Proprietorship #190823

In [4]:
df_account.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2087786 entries, 0 to 2087785
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   Bank Name       object
 1   Bank ID         int64
 2   Account Number  object
 3   Entity ID       object
 4   Entity Name     object
dtypes: int64(1), object(4)
memory usage: 79.6+ MB

In [5]:
df_account['Bank Name'] = df_account['Bank Name'].str.strip()

In [6]:
df_account['Account Number'] = df_account['Account Number'].astype(str).str.strip().str.upper()

In [7]:
df_account['Entity ID'] = df_account['Entity ID'].astype(str).str.strip().str.upper()

In [8]:
df_account['Entity type'] = df_account['Entity Name'].str.extract(r'(^[A-Za-z ]+)')

df_account['Entity Number'] = df_account['Entity Name'].str.extract(r'(\d+)$')

In [9]:
df_account['Account_type'] = df_account['Account Number'].apply(lambda x: 'Alphanumeric' if any(c.isalpha() for c in x) else 'Numeric')

In [10]:
df_account.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2087786 entries, 0 to 2087785
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   Bank Name       object
 1   Bank ID         int64
 2   Account Number  object
 3   Entity ID       object
 4   Entity Name     object
 5   Entity type     object
 6   Entity Number   object
 7   Account_type    object
dtypes: int64(1), object(7)
memory usage: 127.4+ MB

In [11]:
df_account.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name,Entity type,Entity Number,Account_type
0,China Bank #561,53267,817D00980,2AA1F24F180,Corporation #183669,Corporation,183669,Alphanumeric
1,Spain Bank #18657,316997,808BB2280,2AA1EEB8540,Partnership #193780,Partnership,193780,Alphanumeric
2,First Bank of Helena,339367,8505ED380,2AA206D7790,Sole Proprietorship #4078,Sole Proprietorship,4078,Alphanumeric
3,Mexico Bank #3367,3148419,8363D4180,2AA2001B1A0,Partnership #133577,Partnership,133577,Alphanumeric
4,Switzerland Bank #2372,3174937,842090C80,2AA20224CB0,Sole Proprietorship #190823,Sole Proprietorship,190823,Alphanumeric

In [12]:
df_account.isnull().sum()

Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
Entity type       0
Entity Number     0
Account_type      0
dtype: int64

In [13]:
df_account.columns = df_account.columns.str.lower()
df_account.columns = df_account.columns.str.replace(" ", "_")

In [14]:
df_account.columns

Index(['bank_name', 'bank_id', 'account_number', 'entity_id', 'entity_name',
       'entity_type', 'entity_number', 'account_type'],
      dtype='object')

In [15]:
# from sqlalchemy import create_engine

# engine = create_engine(f"postgresql+psycopg2://postgres:25012004@localhost:5433/AML_Project")

# df_account.head(0).to_sql('aml_account', engine, if_exists='replace', index=False)

In [16]:
# df_account.to_csv('account_clean.csv', index=False)

In [17]:
# import psycopg2

# conn = psycopg2.connect(host = "localhost", 
#                 port = "5433",
#                 database = "AML_Project",
#                 user = "postgres",
#                 password = "25012004" 
# )

# cursor = conn.cursor()

# with open(r"C:\Users\sudhanshu\Downloads\Prajwal Sonekar\account_clean.csv","r") as f:
#     cursor.copy_expert("COPY aml_account FROM STDIN WITH CSV HEADER",f)

# conn.commit()
# cursor.close()
# conn.close()